// Generated by gencpp from file learning_topic/add_two_ints.msg
// DO NOT EDIT!


#ifndef LEARNING_TOPIC_MESSAGE_ADD_TWO_INTS_H
#define LEARNING_TOPIC_MESSAGE_ADD_TWO_INTS_H

#include <ros/service_traits.h>


#include <learning_topic/add_two_intsRequest.h>
#include <learning_topic/add_two_intsResponse.h>


namespace learning_topic
{

struct add_two_ints
{

typedef add_two_intsRequest Request;
typedef add_two_intsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_two_ints
} // namespace learning_topic


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_topic::add_two_ints > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learning_topic::add_two_ints&) { return value(); }
};

template<>
struct DataType< ::learning_topic::add_two_ints > {
  static const char* value()
  {
    return "learning_topic/add_two_ints";
  }

  static const char* value(const ::learning_topic::add_two_ints&) { return value(); }
};


// service_traits::MD5Sum< ::learning_topic::add_two_intsRequest> should match 
// service_traits::MD5Sum< ::learning_topic::add_two_ints > 
template<>
struct MD5Sum< ::learning_topic::add_two_intsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_topic::add_two_ints >::value();
  }
  static const char* value(const ::learning_topic::add_two_intsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_topic::add_two_intsRequest> should match 
// service_traits::DataType< ::learning_topic::add_two_ints > 
template<>
struct DataType< ::learning_topic::add_two_intsRequest>
{
  static const char* value()
  {
    return DataType< ::learning_topic::add_two_ints >::value();
  }
  static const char* value(const ::learning_topic::add_two_intsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_topic::add_two_intsResponse> should match 
// service_traits::MD5Sum< ::learning_topic::add_two_ints > 
template<>
struct MD5Sum< ::learning_topic::add_two_intsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_topic::add_two_ints >::value();
  }
  static const char* value(const ::learning_topic::add_two_intsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_topic::add_two_intsResponse> should match 
// service_traits::DataType< ::learning_topic::add_two_ints > 
template<>
struct DataType< ::learning_topic::add_two_intsResponse>
{
  static const char* value()
  {
    return DataType< ::learning_topic::add_two_ints >::value();
  }
  static const char* value(const ::learning_topic::add_two_intsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_TOPIC_MESSAGE_ADD_TWO_INTS_H
