// Generated by gencpp from file learning_topic/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LEARNING_TOPIC_MESSAGE_ADDTWOINTS_H
#define LEARNING_TOPIC_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <learning_topic/AddTwoIntsRequest.h>
#include <learning_topic/AddTwoIntsResponse.h>


namespace learning_topic
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace learning_topic


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_topic::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learning_topic::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::learning_topic::AddTwoInts > {
  static const char* value()
  {
    return "learning_topic/AddTwoInts";
  }

  static const char* value(const ::learning_topic::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::learning_topic::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::learning_topic::AddTwoInts > 
template<>
struct MD5Sum< ::learning_topic::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_topic::AddTwoInts >::value();
  }
  static const char* value(const ::learning_topic::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_topic::AddTwoIntsRequest> should match 
// service_traits::DataType< ::learning_topic::AddTwoInts > 
template<>
struct DataType< ::learning_topic::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::learning_topic::AddTwoInts >::value();
  }
  static const char* value(const ::learning_topic::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_topic::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::learning_topic::AddTwoInts > 
template<>
struct MD5Sum< ::learning_topic::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_topic::AddTwoInts >::value();
  }
  static const char* value(const ::learning_topic::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_topic::AddTwoIntsResponse> should match 
// service_traits::DataType< ::learning_topic::AddTwoInts > 
template<>
struct DataType< ::learning_topic::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::learning_topic::AddTwoInts >::value();
  }
  static const char* value(const ::learning_topic::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_TOPIC_MESSAGE_ADDTWOINTS_H
